In [1]:
import numpy as np
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.structure import Structure
from mp_api.client import MPRester

In [2]:
mp_key = "rp4DtuzKYSzwLoY22WqkCtwvk1sjt8F3"
mp_id = "mp-15781"

In [3]:
with MPRester(mp_key) as m :
    structure = m.get_structure_by_material_id(mp_id)

    
analyzer = SpacegroupAnalyzer(structure)
primitive_structure = analyzer.get_primitive_standard_structure()

direct_lattice_vectors = primitive_structure.lattice.matrix

# Calcul des vecteurs de base du réseau réciproque
reciprocal_lattice_vectors = np.linalg.inv(direct_lattice_vectors).T * 2 * np.pi

print("Vecteurs de base du réseau direct:")
print(direct_lattice_vectors)

print("\nVecteurs de base du réseau réciproque:")
print(reciprocal_lattice_vectors)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Vecteurs de base du réseau direct:
[[ 7.40564222 -2.14565931  0.        ]
 [ 7.40564222  2.14565931  0.        ]
 [ 6.78397381  0.          3.66402648]]

Vecteurs de base du réseau réciproque:
[[ 0.4242161  -1.46416192 -0.78543944]
 [ 0.4242161   1.46416192 -0.78543944]
 [ 0.          0.          1.71483076]]


In [4]:
lattice_type = analyzer.get_lattice_type()
crystal_system = analyzer.get_crystal_system()
point_group = analyzer.get_point_group_symbol()
print("\nType de maille:", lattice_type)
print("Système cristallin:", crystal_system)
print("Groupe ponctuel:", point_group)


Type de maille: rhombohedral
Système cristallin: trigonal
Groupe ponctuel: -3m
