In [1]:
import numpy as np
from mp_api.client import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from jupyter_jsmol.pymatgen import quick_view
from jupyter_jsmol import JsmolView

In [2]:
!jupyter nbextension enable --py jupyter_jsmol

Enabling notebook extension jupyter-jsmol/extension...
      - Validating: OK


In [3]:
mp_key = "rp4DtuzKYSzwLoY22WqkCtwvk1sjt8F3"
mp_id = "mp-15781"

In [4]:
with MPRester(mp_key) as m:
    # Récupérer la structure du matériau
    structure = m.get_structure_by_material_id(mp_id)

# Analyse du groupe spatial
analyzer = SpacegroupAnalyzer(structure)

conv_struc = analyzer.get_conventional_standard_structure()
symmops = SpacegroupAnalyzer(conv_struc).get_space_group_operations()
selected_ops = symmops[1:4]

atoms = conv_struc.sites[:3]

# Appliquer les opérations de symétrie et visualiser avec jupyter-jsmol
for op, atom in zip(selected_ops, atoms):
    transformed_site = op.operate(atom.frac_coords)
    print(f"Opération : {op}")
    print(f"Atome original : {np.round(atom.frac_coords, 3)}")
    print(f"Atome transformé : {np.round(transformed_site, 3)}\n")
    view = quick_view(structure)
    display(view)

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

Opération : Rot:
[[-1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Atome original : [0.333 0.667 0.167]
Atome transformé : [-0.333 -0.667 -0.167]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Opération : Rot:
[[ 0. -1.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]
tau
[0. 0. 0.]
Atome original : [1.  1.  0.5]
Atome transformé : [-1.   0.   0.5]



JsmolView(layout=Layout(align_self='stretch', height='400px'))

Opération : Rot:
[[ 0.  1.  0.]
 [-1.  1.  0.]
 [ 0.  0. -1.]]
tau
[0. 0. 0.]
Atome original : [0.667 0.333 0.833]
Atome transformé : [ 0.333 -0.333 -0.833]



JsmolView(layout=Layout(align_self='stretch', height='400px'))